version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
    environment:
      MONGO_URI: "mongodb://admin:admin@mongodb:27017/chat_db?authSource=admin"
      DB_NAME: "chat_db"
      COLLECTION_NAME: "messages"
      SUPABASEURL: "http://localhost:54321"
      SUPABASEKEY: ""
    depends_on:
      - mongodb
    command: sh -c "go mod tidy && go run main.go"

  mongodb:
    image: mongo:7
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: chat_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
