version: "3.9"

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      MONGO_URI: "mongodb://admin:admin@mongodb:27017/chat_db?authSource=admin"
    depends_on:
      - mongodb

  mongodb:
    image: mongo:7
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: chat_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./mongo-init/:/docker-entrypoint-initdb.d/

volumes:
  mongo_data:
